### ISSUE TITLE
Graph labels and title are dark on dark

### ISSUE THREAD

**Issue by flazouh** [johnnybarrels/jupyterlab_onedarkpro#1]
<img width="664" alt="Screenshot 2020-12-14 at 10 17 40" src="https://user-images.githubusercontent.com/25705704/102056811-9ae65400-3df5-11eb-82c4-7da4f22da7d2.png">
Is there a way to put that in white ?

**Comment by johnnybarrels** [comment]
This actually has nothing to do with the theme, matplotlib just defaults to black fonts and a transparent facecolor, which is always a nuisance with dark themes. You just need to set one of these to white; a quick Google of “matplotlib change font color” or “matplotlib change facecolor” will have plenty of info

**Comment by johnnybarrels** [comment]
Apologies, issue #3 highlighted that this was in fact an issue with the theme itself. Please see that issue for the resolution.

**Comment by flazouh** [comment]
Oh! I see, well, thanks a lot, will take a look at it.
