### ISSUE TITLE
Plots axes background are darkened and text are invisiable

### ISSUE THREAD

**Issue by 0liu** [johnnybarrels/jupyterlab_onedarkpro#3]
Thank you for the great theme!
I am having an issue with plots display. The axes background are all in dark and merged with foreground text, so labels are invisible. No such problem with the default dark theme. Attached two screenshots to show it.

![onedark](https://user-images.githubusercontent.com/4315932/104828263-4da63980-581c-11eb-9acb-c2b14a42f43d.png)
![jupyter_dark](https://user-images.githubusercontent.com/4315932/104828265-526aed80-581c-11eb-8aad-d272a9ea47c3.png)

**Comment by johnnybarrels** [comment]
Now that is interesting. I was always aware of that behaviour in my theme (and workaround accordingly), but never noticed that no such issue occurs in the default dark theme.

For now, try setting `mpl.rcParams['figure.facecolor'] = 'white'`, while I look into it! Cheers

<img width="496" alt="Screen Shot 2021-01-17 at 9 38 56 am" src="https://user-images.githubusercontent.com/49610004/104828838-4f1d4380-58a8-11eb-9c72-df64ee20b6a6.png">

**Comment by johnnybarrels** [comment]
This has now been resolved, but the updated package now requires the newly released Jupyter Lab 3.

You have two options to use the updated theme:

1. Upgrade to Jupyter Lab 3
    - `pip install -U jupyterlab`
    - Install the theme via the Extensions tab as per usual

2. Stay using Jupyter Lab 2
    - Download the updated `index.css` file from this repository
    - Navigate to the theme directory
        - On macOS this is `/Library/Frameworks/Python.framework/Versions/3.X/share/jupyter/lab/themes/jupyterlab_onedarkpro`
    - Replace the `index.css` file with the updated one from this repo
